modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="sinistra"
version="1.0.0"
displayName="Sinistra"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Sebi, MCreator"

[[dependencies.sinistra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



